
trigger:
  - master

variables:
- group: version_group
pool:
  vmImage: 'ubuntu-latest'


steps:
  - checkout: none
  - bash: |
      ver=$((ver+1))
      echo "##vso[task.setvariable variable=version"ver]
    env:
      ver: $version 
  - bash: |
      echo $ver
    env:
      ver: $version