
trigger:
  - master

variables:
- group: version_group
- name: ver1
  value: 2
pool:
  vmImage: 'ubuntu-latest'


steps:
  - checkout: none
  - bash: |
      ver=$((ver+1))
      echo "##vso[task.setvariable variable=version"$ver]
    env:
      ver: $(ver1) 
  - bash: |
      echo $ver
    env:
      ver: $(ver1)