resources:
  pipelines: 'MyShuttle'
trigger: none
variables:
  count: $[counter('cnt',0)]
pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: echo Hello, world!
  displayName: 'Run a one-line script'
  env:
    cnt: $(count)