trigger: none
resources:
  pipelines: 
  - pipeline: 'BuildPipeline'
    source: 'MyShuttle'
    trigger: true
variables:
  count: $[counter('cnt',0)]
  
pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: echo $cnt
  displayName: 'Echo counter'
  env:
    cnt: $(count)