
name: MyShuttle-CICD

on: 
  push:
    branches: 
      - master
      - gren-dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
       java-version: 1.8
       java-package: jdk
    - name: Build App
      run: mvn -f pom.xml clean package
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
       name: myshuttle
       path: target/*.war
