
name: MyShuttle-CICD

on: 
  push:
    branches: master
      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1
    
    
    - name: Setup Java JDK
      uses: actions/setup-java@v3.3.0
      with:
        java-version: 11
        distribution: adopt
        cache: maven

    - name: Build App
      run: mvn -f pom.xml --batch-mode --update-snapshots verify
    
    - name: Run Junit Tests
      run: mvn -B test --file pom.xml  
    
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: test/test-results.xml  
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
       name: myshuttle
       path: target/myshuttle.war

#=========================================================================================================

#   deploy:
#     runs-on: [self-hosted, production]
#     needs: build
#     name: DEPLOY TO AZURE VM
#     steps:
#       - name: Download Artifacts
#         uses: actions/download-artifact@v1.0.0
#         with:
#          name: myshuttle
      
#       - name: Deploy to Tomcat
#         working-directory: myshuttle
#         run:
#          sudo curl -v -u ${{secrets.TOMCAT_USER}}:${{secrets.TOMCAT_PASSWORD}} -T myshuttle.war "http://localhost:${{secrets.TOMCAT_PORT}}/manager/text/deploy?path=/myshuttle&update=true"
     
