
name: MyShuttle.Maven

on: 
  push:
    branches: [master]
      
jobs:
  build:
    name: 🧪 Build
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Build App
      run: mvn -f pom.xml -DskipITs package
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
       name: myshuttle
       path: target/myshuttle.war

  code-analysis:
     name: 🔆 Code Analysis
     runs-on: ubuntu-latest
     needs: [build]
     steps:
     
     - name: Checkout
       uses: actions/checkout@v2
       with:
         # Make sure the actual branch is checked out when running on pull requests
         ref: ${{ github.head_ref }}
    
     - name: SonarCloud Scan
       uses: sonarsource/sonarcloud-github-action@v1.5
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#=========================================================================================================

#   deploy:
#     runs-on: [self-hosted, production]
#     needs: build
#     name: DEPLOY TO AZURE VM
#     steps:
#       - name: Download Artifacts
#         uses: actions/download-artifact@v1.0.0
#         with:
#          name: myshuttle
      
#       - name: Deploy to Tomcat
#         working-directory: myshuttle
#         run:
#          sudo curl -v -u ${{secrets.TOMCAT_USER}}:${{secrets.TOMCAT_PASSWORD}} -T myshuttle.war "http://localhost:${{secrets.TOMCAT_PORT}}/manager/text/deploy?path=/myshuttle&update=true"
     
